-- leader key needs to be set before lazy nvim initialization
require("dominik.remap")
require("dominik.set")
require("dominik.lazy")
require("dominik.design")
require("dominik.telescope")
require("dominik.harpoon")
require("dominik.undotree")
require("dominik.fugitive")
require("dominik.lsp")
require("dominik.copilot")
